runtime: nodejs20

# env_variables:
#   NODE_ENV: "production"
  # OPENAI_API_KEY: "your-api-key-here"
  # MONGODB_URI: "your-mongo-uri-here"

handlers:
  - url: /.*
    script: auto
    
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /
    static_dir: dist

  - url: /
    static_files: dist/\1
    upload: dist/(.*)